// Generated by CIRCT firtool-1.128.0
module AsyncInstMem(	// src/main/scala/main.scala:93:7
  input  [7:0]  io_addr,	// src/main/scala/main.scala:94:14
  output [31:0] io_inst	// src/main/scala/main.scala:94:14
);

  wire [255:0][31:0] _GEN =
    '{32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h13,
      32'h897,
      32'hFF7A813,
      32'h500793,
      32'h359713,
      32'hFF5C693,
      32'hFF5F613,
      32'hFFF00593,
      32'h629533,
      32'h42B4B3,
      32'h42C433,
      32'h42E3B3,
      32'h42F333,
      32'h11128293,
      32'h111112B7,
      32'h40218233,
      32'h2081B3,
      32'h32110113,
      32'h87654137,
      32'h67808093,
      32'h123450B7};	// src/main/scala/main.scala:123:11
  assign io_inst = _GEN[io_addr];	// src/main/scala/main.scala:93:7, :123:11
endmodule


// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RegisterFile(	// src/main/scala/main.scala:69:7
  input         clock,	// src/main/scala/main.scala:69:7
                reset,	// src/main/scala/main.scala:69:7
  input  [4:0]  io_rs1,	// src/main/scala/main.scala:70:14
                io_rs2,	// src/main/scala/main.scala:70:14
                io_waddr,	// src/main/scala/main.scala:70:14
  input  [31:0] io_wdata,	// src/main/scala/main.scala:70:14
  output [31:0] io_rdata1,	// src/main/scala/main.scala:70:14
                io_rdata2	// src/main/scala/main.scala:70:14
);

  reg  [31:0]       regs_1;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_2;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_3;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_4;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_5;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_6;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_7;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_8;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_9;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_10;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_11;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_12;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_13;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_14;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_15;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_16;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_17;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_18;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_19;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_20;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_21;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_22;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_23;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_24;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_25;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_26;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_27;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_28;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_29;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_30;	// src/main/scala/main.scala:80:21
  reg  [31:0]       regs_31;	// src/main/scala/main.scala:80:21
  wire [31:0][31:0] _GEN =
    {{regs_31},
     {regs_30},
     {regs_29},
     {regs_28},
     {regs_27},
     {regs_26},
     {regs_25},
     {regs_24},
     {regs_23},
     {regs_22},
     {regs_21},
     {regs_20},
     {regs_19},
     {regs_18},
     {regs_17},
     {regs_16},
     {regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {32'h0}};	// src/main/scala/main.scala:80:21, :86:19
  always @(posedge clock) begin	// src/main/scala/main.scala:69:7
    if (reset) begin	// src/main/scala/main.scala:69:7
      regs_1 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_2 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_3 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_4 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_5 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_6 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_7 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_8 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_9 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_10 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_11 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_12 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_13 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_14 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_15 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_16 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_17 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_18 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_19 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_20 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_21 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_22 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_23 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_24 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_25 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_26 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_27 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_28 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_29 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_30 <= 32'h0;	// src/main/scala/main.scala:80:21
      regs_31 <= 32'h0;	// src/main/scala/main.scala:80:21
    end
    else begin	// src/main/scala/main.scala:69:7
      if ((|io_waddr) & io_waddr == 5'h1)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_1 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h2)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_2 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h3)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_3 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h4)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_4 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h5)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_5 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h6)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_6 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h7)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_7 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h8)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_8 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h9)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_9 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hA)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_10 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hB)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_11 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hC)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_12 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hD)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_13 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hE)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_14 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'hF)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_15 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h10)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_16 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h11)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_17 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h12)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_18 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h13)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_19 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h14)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_20 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h15)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_21 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h16)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_22 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h17)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_23 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h18)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_24 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h19)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_25 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h1A)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_26 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h1B)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_27 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h1C)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_28 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h1D)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_29 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & io_waddr == 5'h1E)	// src/main/scala/main.scala:69:7, :80:21, :82:{28,37}, :83:20
        regs_30 <= io_wdata;	// src/main/scala/main.scala:80:21
      if ((|io_waddr) & (&io_waddr))	// src/main/scala/main.scala:80:21, :82:{28,37}, :83:20
        regs_31 <= io_wdata;	// src/main/scala/main.scala:80:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/main.scala:69:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/main.scala:69:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/main.scala:69:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/main.scala:69:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/main.scala:69:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/main.scala:69:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/main.scala:69:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/main.scala:69:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/main.scala:69:7
        end	// src/main/scala/main.scala:69:7
        regs_1 = _RANDOM[5'h1];	// src/main/scala/main.scala:69:7, :80:21
        regs_2 = _RANDOM[5'h2];	// src/main/scala/main.scala:69:7, :80:21
        regs_3 = _RANDOM[5'h3];	// src/main/scala/main.scala:69:7, :80:21
        regs_4 = _RANDOM[5'h4];	// src/main/scala/main.scala:69:7, :80:21
        regs_5 = _RANDOM[5'h5];	// src/main/scala/main.scala:69:7, :80:21
        regs_6 = _RANDOM[5'h6];	// src/main/scala/main.scala:69:7, :80:21
        regs_7 = _RANDOM[5'h7];	// src/main/scala/main.scala:69:7, :80:21
        regs_8 = _RANDOM[5'h8];	// src/main/scala/main.scala:69:7, :80:21
        regs_9 = _RANDOM[5'h9];	// src/main/scala/main.scala:69:7, :80:21
        regs_10 = _RANDOM[5'hA];	// src/main/scala/main.scala:69:7, :80:21
        regs_11 = _RANDOM[5'hB];	// src/main/scala/main.scala:69:7, :80:21
        regs_12 = _RANDOM[5'hC];	// src/main/scala/main.scala:69:7, :80:21
        regs_13 = _RANDOM[5'hD];	// src/main/scala/main.scala:69:7, :80:21
        regs_14 = _RANDOM[5'hE];	// src/main/scala/main.scala:69:7, :80:21
        regs_15 = _RANDOM[5'hF];	// src/main/scala/main.scala:69:7, :80:21
        regs_16 = _RANDOM[5'h10];	// src/main/scala/main.scala:69:7, :80:21
        regs_17 = _RANDOM[5'h11];	// src/main/scala/main.scala:69:7, :80:21
        regs_18 = _RANDOM[5'h12];	// src/main/scala/main.scala:69:7, :80:21
        regs_19 = _RANDOM[5'h13];	// src/main/scala/main.scala:69:7, :80:21
        regs_20 = _RANDOM[5'h14];	// src/main/scala/main.scala:69:7, :80:21
        regs_21 = _RANDOM[5'h15];	// src/main/scala/main.scala:69:7, :80:21
        regs_22 = _RANDOM[5'h16];	// src/main/scala/main.scala:69:7, :80:21
        regs_23 = _RANDOM[5'h17];	// src/main/scala/main.scala:69:7, :80:21
        regs_24 = _RANDOM[5'h18];	// src/main/scala/main.scala:69:7, :80:21
        regs_25 = _RANDOM[5'h19];	// src/main/scala/main.scala:69:7, :80:21
        regs_26 = _RANDOM[5'h1A];	// src/main/scala/main.scala:69:7, :80:21
        regs_27 = _RANDOM[5'h1B];	// src/main/scala/main.scala:69:7, :80:21
        regs_28 = _RANDOM[5'h1C];	// src/main/scala/main.scala:69:7, :80:21
        regs_29 = _RANDOM[5'h1D];	// src/main/scala/main.scala:69:7, :80:21
        regs_30 = _RANDOM[5'h1E];	// src/main/scala/main.scala:69:7, :80:21
        regs_31 = _RANDOM[5'h1F];	// src/main/scala/main.scala:69:7, :80:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/main.scala:69:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/main.scala:69:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata1 = io_rs1 == 5'h0 ? 32'h0 : _GEN[io_rs1];	// src/main/scala/main.scala:69:7, :86:{19,27}
  assign io_rdata2 = io_rs2 == 5'h0 ? 32'h0 : _GEN[io_rs2];	// src/main/scala/main.scala:69:7, :86:19, :87:{19,27}
endmodule

module ALU(	// src/main/scala/main.scala:24:7
  input  [31:0] io_a,	// src/main/scala/main.scala:25:14
                io_b,	// src/main/scala/main.scala:25:14
  input  [3:0]  io_aluOp,	// src/main/scala/main.scala:25:14
  output [31:0] io_out,	// src/main/scala/main.scala:25:14
  output        io_zf,	// src/main/scala/main.scala:25:14
                io_of	// src/main/scala/main.scala:25:14
);

  wire [62:0]       _res_T_4 = {31'h0, io_a} << io_b[4:0];	// src/main/scala/main.scala:34:19, :40:35
  wire [31:0]       _GEN = {27'h0, io_b[4:0]};	// src/main/scala/main.scala:34:19, :46:35
  wire [15:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {$signed($signed(io_a) >>> _GEN)},
     {io_a - io_b},
     {io_a & io_b},
     {io_a | io_b},
     {io_a >> _GEN},
     {io_a ^ io_b},
     {{31'h0, io_a < io_b}},
     {{31'h0, $signed(io_a) < $signed(io_b)}},
     {_res_T_4[31:0]},
     {io_a + io_b}};	// src/main/scala/main.scala:35:26, :37:20, :38:{27,35}, :39:{27,35}, :40:{27,35}, :41:{27,46}, :42:{27,39}, :43:{27,35}, :44:{27,35}, :45:{27,35}, :46:{27,35}, :47:{27,43}
  assign io_out = _GEN_0[io_aluOp];	// src/main/scala/main.scala:24:7, :35:26, :37:20, :38:27, :39:27, :40:27, :41:27, :42:27, :43:27, :44:27, :45:27, :46:27, :47:27
  assign io_zf = _GEN_0[io_aluOp] == 32'h0;	// src/main/scala/main.scala:24:7, :35:26, :37:20, :38:27, :39:27, :40:27, :41:27, :42:27, :43:27, :44:27, :45:27, :46:27, :47:27, :51:18
  assign io_of =
    io_aluOp == 4'h0
      ? io_a[31] == io_b[31] & _GEN_0[io_aluOp][31] != io_a[31]
      : io_aluOp == 4'h8 & io_a[31] != io_b[31] & _GEN_0[io_aluOp][31] != io_a[31];	// src/main/scala/main.scala:24:7, :35:26, :37:20, :38:27, :39:27, :40:27, :41:27, :42:27, :43:27, :44:27, :45:27, :46:27, :47:27, :54:19, :55:19, :56:18, :58:9, :59:34, :60:{11,21,32,42}, :61:41, :62:{11,21,32,42}
endmodule

module SingleCycleCPU(	// src/main/scala/main.scala:129:7
  input         clock,	// src/main/scala/main.scala:129:7
                reset,	// src/main/scala/main.scala:129:7
  output        io_zf,	// src/main/scala/main.scala:130:14
                io_of,	// src/main/scala/main.scala:130:14
  output [31:0] io_aluResult,	// src/main/scala/main.scala:130:14
                io_currentInst,	// src/main/scala/main.scala:130:14
                io_currentPC	// src/main/scala/main.scala:130:14
);

  wire [31:0]     _alu_io_out;	// src/main/scala/main.scala:227:19
  wire [31:0]     _regFile_io_rdata1;	// src/main/scala/main.scala:201:23
  wire [31:0]     _regFile_io_rdata2;	// src/main/scala/main.scala:201:23
  wire [31:0]     _imem_io_inst;	// src/main/scala/main.scala:143:20
  reg  [31:0]     pc;	// src/main/scala/main.scala:139:23
  wire            isRType = _imem_io_inst[6:0] == 7'h33;	// src/main/scala/main.scala:143:20, :151:20, :161:25
  wire            isLUI = _imem_io_inst[6:0] == 7'h37;	// src/main/scala/main.scala:143:20, :151:20, :163:25
  wire            isAUIPC = _imem_io_inst[6:0] == 7'h17;	// src/main/scala/main.scala:143:20, :151:20, :164:25
  wire [7:0][3:0] _GEN =
    {{4'h7},
     {4'h6},
     {4'hA},
     {4'h4},
     {4'h3},
     {4'h2},
     {4'h1},
     {{_imem_io_inst[31:25] == 7'h20, 3'h0}}};	// src/main/scala/main.scala:143:20, :156:20, :168:9, :172:21, :174:{22,40}, :175:17, :177:17, :180:29, :181:29, :182:29, :183:29, :184:29, :185:29
  wire            _GEN_0 = isLUI | isAUIPC;	// src/main/scala/main.scala:163:25, :164:25, :194:22
  always @(posedge clock) begin	// src/main/scala/main.scala:129:7
    if (reset)	// src/main/scala/main.scala:129:7
      pc <= 32'h0;	// src/main/scala/main.scala:139:23
    else	// src/main/scala/main.scala:129:7
      pc <= pc + 32'h4;	// src/main/scala/main.scala:139:23, :140:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/main.scala:129:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/main.scala:129:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/main.scala:129:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/main.scala:129:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/main.scala:129:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/main.scala:129:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/main.scala:129:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/main.scala:129:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/main.scala:129:7
        pc = _RANDOM[/*Zero width*/ 1'b0];	// src/main/scala/main.scala:129:7, :139:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/main.scala:129:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/main.scala:129:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AsyncInstMem imem (	// src/main/scala/main.scala:143:20
    .io_addr (pc[9:2]),	// src/main/scala/main.scala:139:23, :144:21
    .io_inst (_imem_io_inst)
  );	// src/main/scala/main.scala:143:20
  RegisterFile regFile (	// src/main/scala/main.scala:201:23
    .clock     (clock),
    .reset     (reset),
    .io_rs1    (_imem_io_inst[19:15]),	// src/main/scala/main.scala:143:20, :154:20
    .io_rs2    (_imem_io_inst[24:20]),	// src/main/scala/main.scala:143:20, :155:20
    .io_waddr  (_imem_io_inst[11:7]),	// src/main/scala/main.scala:143:20, :152:20
    .io_wdata  (_alu_io_out),	// src/main/scala/main.scala:227:19
    .io_rdata1 (_regFile_io_rdata1),
    .io_rdata2 (_regFile_io_rdata2)
  );	// src/main/scala/main.scala:201:23
  ALU alu (	// src/main/scala/main.scala:227:19
    .io_a     (isAUIPC ? pc : isLUI ? 32'h0 : _regFile_io_rdata1),	// src/main/scala/main.scala:139:23, :163:25, :164:25, :201:23, :210:18, :211:10, :212:23, :213:10, :215:10
    .io_b
      (isRType
         ? _regFile_io_rdata2
         : _GEN_0
             ? {_imem_io_inst[31:12], 12'h0}
             : {{20{_imem_io_inst[31]}}, _imem_io_inst[31:20]}),	// src/main/scala/main.scala:143:20, :158:{17,22,31,42}, :159:{17,22}, :161:25, :194:22, :201:23, :218:18, :219:10, :220:34, :221:10, :223:10
    .io_aluOp
      (isRType
         ? _GEN[_imem_io_inst[14:12]]
         : _imem_io_inst[6:0] == 7'h13
             ? (_imem_io_inst[14:12] == 3'h0
                  ? 4'h0
                  : _imem_io_inst[14:12] == 3'h1
                      ? 4'h1
                      : {_imem_io_inst[14:12] != 3'h2, 3'h2})
             : _GEN_0 ? 4'h0 : 4'hA),	// src/main/scala/main.scala:143:20, :151:20, :153:20, :161:25, :162:25, :168:9, :171:18, :172:21, :174:40, :180:29, :181:29, :182:29, :183:29, :184:29, :185:29, :187:25, :188:21, :189:29, :190:29, :191:29, :194:{22,34}, :195:11, :197:11
    .io_out   (_alu_io_out),
    .io_zf    (io_zf),
    .io_of    (io_of)
  );	// src/main/scala/main.scala:227:19
  assign io_aluResult = _alu_io_out;	// src/main/scala/main.scala:129:7, :227:19
  assign io_currentInst = _imem_io_inst;	// src/main/scala/main.scala:129:7, :143:20
  assign io_currentPC = pc;	// src/main/scala/main.scala:129:7, :139:23
endmodule


// ----- 8< ----- FILE "verification/layers-SingleCycleCPU-Verification.sv" ----- 8< -----

// Generated by CIRCT firtool-1.128.0
`ifndef layers_SingleCycleCPU_Verification	// src/main/scala/main.scala:129:7
  `define layers_SingleCycleCPU_Verification
`endif // not def layers_SingleCycleCPU_Verification

// ----- 8< ----- FILE "verification/assert/layers-SingleCycleCPU-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.128.0
`ifndef layers_SingleCycleCPU_Verification_Assert	// src/main/scala/main.scala:129:7
  `define layers_SingleCycleCPU_Verification_Assert
  `include "layers-SingleCycleCPU-Verification.sv"	// src/main/scala/main.scala:129:7
`endif // not def layers_SingleCycleCPU_Verification_Assert

// ----- 8< ----- FILE "verification/assume/layers-SingleCycleCPU-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.128.0
`ifndef layers_SingleCycleCPU_Verification_Assume	// src/main/scala/main.scala:129:7
  `define layers_SingleCycleCPU_Verification_Assume
  `include "layers-SingleCycleCPU-Verification.sv"	// src/main/scala/main.scala:129:7
`endif // not def layers_SingleCycleCPU_Verification_Assume

// ----- 8< ----- FILE "verification/cover/layers-SingleCycleCPU-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.128.0
`ifndef layers_SingleCycleCPU_Verification_Cover	// src/main/scala/main.scala:129:7
  `define layers_SingleCycleCPU_Verification_Cover
  `include "layers-SingleCycleCPU-Verification.sv"	// src/main/scala/main.scala:129:7
`endif // not def layers_SingleCycleCPU_Verification_Cover
